baseURL = "https://shreyaspotnis.github.io/ourquantumuniverse/"
languageCode = "en-us"
title = "Our Quantum Universe"

[params]
  description = "Notes for myself"
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"], ["$", "$"]]
